name: Makefile CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup config
      run: echo "auth sufficient pam_permit.so" | sudo tee /etc/pam.d/supra

    - name: setup conf
      run: echo "account sufficient pam_permit.so" | sudo tee -a /etc/pam.d/supra

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y build-essential libpam0g-dev

    - name: Build program
      run: make perms

    - name: Run check
      run: make check
